CREATE TABLE Player
(
    PID INT,
    Name TEXT NOT NULL,
    Sport VARCHAR(10) NOT NULL,
    Gender CHAR(1) NOT NULL,
    Active BOOLEAN NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Equipment
(
    EID INT,
    Name TEXT NOT NULL,
    Location TEXT NOT NULL,
    Quantity INT NOT NULL,
    Description TEXT,
    PRIMARY KEY (EID)
);

CREATE TABLE Worker
(
    WID INT,
    Name TEXT NOT NULL,
    Grade VARCHAR(10) NOT NULL,
    Sport VARCHAR(10) NOT NULL,
    Email TEXT NOT NULL,
    PRIMARY KEY (WID)
);

CREATE TABLE Visits
(
    VID INT,
    Year INT NOT NULL,
    Month VARCHAR(12) NOT NULL,
    Day INT NOT NULL,
    Time DECIMAL NOT NULL,
    PID INT NOT NULL,
    EID INT NOT NULL,
    WID INT NOT NULL,
    PRIMARY KEY (VID),
    FOREIGN KEY (PID) REFERENCES Player(PID),
    FOREIGN KEY (EID) REFERENCES Equipment(EID),
    FOREIGN KEY (WID) REFERENCES Worker(WID)
);
